= Voice Control

Voice control is also known as voice recognition and speech recognition.

Voice control is one way of controlling a computer or tablet.  No physical movement is required, and the entire computer can be controlled using just your voice.  Voice control used to be something quite unusual that was only used with expensive specialist software.  However, it is now turning up in all sorts of mainstream applications, from Siri on an iPhone to the Amazon echo.

Voice control is available across a range of platforms, including Windows, iOS and android.

When voice control works well and is accurate, it can be a fairly quick way of writing / recording.  [can we expand on this – any comparative measures around? Also decide on terminology around writing / recording]

*What skills do you need to use voice control?*

Using your voice to control a computer is very different to speaking to someone in a face-to-face conversation or chatting with friends. You need to be able to speak at a clear consistent pace, and to use a consistent tone.  

However, the biggest difference is that when writing using voice control, you need to speak in complete sentences.  Written language is different to spoken language and so this will take a bit of getting used to!  The key is to plan what you want to write before you say it. 

*Any contraindications?*

Voice control doesn’t work for everyone, and its not always easy to predict when its not going to work.  However, as technology changes and improves, it may be worth re-visiting in the future even if it is not found to be useful now.

Something about dysarthric speech here..? quiet speech

