= Heading

Issues around using voice control

*Advantages*

As voice control relies solely on speech, it can be an effective means of computer control for people with reduced motor skills.  

It can also be useful for people with visual impairments. Expand - either here or elsewhere.

One of the key advantages of voice control is that it can be used whilst lying in bed, reclining on the sofa, standing up, indeed in any position so long as you are able to speak.  This makes it very flexible for those who have a range of physical needs.

Because the software spells the word it hears, it can work well for people who know what they want to say, but find spelling difficult.      

So long as you know the commands to use, voice control can give full computer control.

*Disadvantages*

It can be very frustrating when the computer misunderstands something you have said, and you have to go back and correct it.

Sometimes words that sound similar can cause problems with accuracy e.g. too and two e.g. need example of two words that are slightly different....

Voice control doesn't always work well in a loud room.  This can make it tricky to use in classroom or workplace environments.

“Training” the computer to recognise your voice can be a lengthy process!


