= Voice Recognition

*What is voice control?*

_Voice control, voice recognition, speech recognition_

•	Voice control provides an alternative method for someone to access a computer when movement can be difficult. It uses only the voice.
•	No physical movement required 
•	Many of the voice control software need to learn a user’s voice before being used- also known as “training”. This is to increase the accuracy and recognise how someone says words. 
•	Voice control is also used for lots of mainstream products such as Siri on your iPhone, or an Amazon echo
•	A good microphone is recommended for use when using voice control. This can increase accuracy and reduce some of the external noise.
•	When voice control works well and is accurate, it can be fairly quick at recording your spoken words
•	There are options to use voice recognition on different platforms such as windows, iOS, android
•	To use voice control you will need to use some exact commands such as “Show desktop”, “drag mouse down faster”, “Press enter”. If you can’t remember them all a cheat sheet next to your computer might be helpful.
•	Voice recognition doesn’t work for everyone, but technology is always changing and may improve in the future

*What skills do you need?*

•	Speaking to write is a very different skill than when you are speaking to communicate in a conversation or with friends.
•	The skill of talking at a clear, consistent pace with a consistent tone. 
•	When writing, planning what you want to say and speaking in complete sentences

*Advantages*

•	Voice control can be used in all positions when you are able to speak; lying in bed, sat on the sofa
•	You can have full computer control (photos, internet, netflix, microsoft, etc)
•	It may be useful for people with visual impairments or reduced motor skills
•	The software spells the word it hears correctly, so if spelling is difficult for you it could help[

*Disadvantages*

•	Unfortunately, voice control does not work for everyone! People with unintelligible speech or quiet speech may find that it doesn’t recognise the words and end up with lots of random words! This can be frustrating.
•	Some words that sound similar could be mistakenly recognised
•	Can be tricky to use in a loud room
•	“Training” the computer to recognise your voice can be a lengthy process!

Detail specific kit examples
Examples include Siri, amazon echo, Dragon dictation

*Videos*
 Dragon in use (iPad?), Plugging in microphone, Voice training example?

Further info;
http://www.bbc.co.uk/accessibility/guides/factsheets/factsheet_VR_intro.pdf
https://www.nuance.com/dragon.html 

