= Setting up and Positioning Voice Control

*Set up*

Most voice control software needs to learn a user’s voice before being used functionally.  This training process improves accuracy and teaches the software how an individual pronounces specific words.  

Insert video of training... 

Accuracy can be helped by using a good quality microphone.  Some microphones can help to filter out background noise if this is an issue.

Insert photograph...

Anything here about help with training for those with dysarthria?

Anything here about set up for someone with a visual impairment?  Presumably can be used with a screen reader for this?

*Positioning*

Other than ensuring that the microphone is accessible and that the individual can see the screen, very little specialist positioning is required.  Because the only muscle movements needed for voice control are those used for speech, voice control can be used while reclining in a comfy chair, from bed, or even walking around so long as a wireless microphone is used.

If someone is using voice control in bed or from a specialist seating system, some sort of mount might be considered to make sure that the individual has a good view of the screen...


