= Introduction to Switches

Define a switch

Control of a switch requires some control over the movement of a body part.  This could be a very light small movement, a large gross movement, or anything in between.   There are a multitude of different switches on the market, and these accommodate different types of movements and pressures.  Some switches (e.g. the suck-puff switch which is controlled by the mouth) are designed to be used with very specific body parts, whereas others can be positioned more flexibly and (sometimes!) creatively.

Talk about bigger isn't always better.

Can include links to Christopher Hills videos

Switch Wizard

Refer to more complex use of switches for full desktop control.

Switches are sometimes incorrectly perceived as being 'babyish'. 

Stephen hawkin using switches - IR switch - did interview Dara O'Brien who was suprprised how slow.  May be also mention tried eye gaze but didn't like.

Full case study of advanced user - see Michael Phillips demo on YT

*What skills do you need to use a switch?* 

control over one movement etc

*Any contraindications?*

;saljfkdl;asf



